FROM node:20.19.4-alpine3.21 as build

RUN mkdir /app

COPY . /app

WORKDIR /app

RUN yarn config set registry https://registry.npmmirror.com && \
    yarn config set network-timeout 600000 && \
    yarn cache clean && \
    yarn install --network-timeout 600000 --network-concurrency 1 || \
    (sleep 5 && yarn install --network-timeout 600000 --network-concurrency 1) || \
    (sleep 10 && yarn install --network-timeout 600000 --network-concurrency 1) && \
    yarn build && \
    tar zcf build.tar.gz ./build

FROM nginx:1.18.0 as release

RUN mkdir /app

COPY --from=build /app/build.tar.gz /app

RUN tar zxf /app/build.tar.gz -C /app && \
    mv /app/build/* /app && \
    rm -rf /app/build* && \
    rm -rf /etc/nginx/conf.d/default.conf

COPY ./w8t.conf /etc/nginx/conf.d

WORKDIR /etc/nginx/

EXPOSE 80

CMD ["nginx","-g","daemon off;"]
